language: haxe

haxe:
 - 4.0.5
 - development

install:
 - haxelib install travix
 - haxelib run travix install

script:
 - haxe build.hxml
 - haxelib run travix node tests-html5.hxml
 - haxelib run travix flash -D exit
