language: haxe

haxe:
 - 4.0.5
 - development

install:
 - haxelib install travix
 - haxelib run travix install
 - haxelib git utest https://github.com/haxe-utest/utest

script:
 - haxe build.hxml
 - haxelib run travix node tests-html5.hxml
#  - haxelib run travix flash -D exit
